version: '3.8'

services:
  sentiment-app:
    build: .
    image: sentiment-analyser:v1
    ports:
      - "8001:80"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=file:/app/mlruns
      - CUDA_VISIBLE_DEVICES=-1
    stdin_open: true
    tty: true
    restart: always
    command: >
      sh -c "uvicorn src.api:app --host 0.0.0.0 --port 80"
    # Use GPU NVIDIA from server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]